version: '3.9'

services:
  web:
    container_name: "mintos-currency-select"
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /web/app
      - /web/app/node_modules
    ports:
      - "8000:8000"
    tty: true
